# Use postgres/example user/password credentials; starts a postgres instance on port 5450 to use as a local db
version: '3.9'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    image: postgres # profiles: ["withpostgres"] only starts when specifying this profile
    container_name: calendso-db
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack
      - calendso-stack

  calcom:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
        - DATABASE_URL=${DATABASE_URL}
      network: stack
    restart: always
    networks:
      - stack
      - calendso-stack
    ports:
      - ${PORT-3000}:3000
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - POSTGRES_PASSWORD = ""
      - POSTGRES_HOST_AUTH_METHOD = trust
    depends_on:
      - database # comment out when using non-docker database (=enabled "withpostgres" profile)
    volumes:
      - "./calendso:/app/"
      - "./scripts:/app/scripts"

# Optional use of Prisma Studio. To use *with* Prisma Studio: 
# docker-compose --profile withstudio up
  studio:
    image: calendso/calendso:latest
    container_name: calendso-studio
    restart: unless-stopped
    profiles: ["withstudio"] # only starts when specifying this profile
    networks:
      - stack
      - calendso-stack
    ports:
      - 5555:5555
    volumes:
      db_data:
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database # comment out when using non-docker database (=enabled "withpostgres" profile)
    command:
      - npx
      - prisma
      - studio
